#ifndef CZKAWKA_BRIDGE_H
#define CZKAWKA_BRIDGE_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef enum CCheckingMethod {
  Hash = 0,
  Name = 1,
  Size = 2,
  SizeName = 3,
} CCheckingMethod;

typedef enum CHashType {
  Blake3 = 0,
  Crc32 = 1,
  Xxh3 = 2,
} CHashType;

typedef struct CzkawkaDuplicateFinder CzkawkaDuplicateFinder;

typedef struct CDuplicateEntry {
  const char *path;
  uint64_t size;
  uint64_t modified_date;
  const char *hash;
} CDuplicateEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct CzkawkaDuplicateFinder *czkawka_duplicate_finder_new(enum CCheckingMethod check_method,
                                                            enum CHashType hash_type,
                                                            bool ignore_hard_links,
                                                            bool use_cache);

void czkawka_duplicate_finder_free(struct CzkawkaDuplicateFinder *finder);

bool czkawka_duplicate_finder_add_directory(struct CzkawkaDuplicateFinder *finder,
                                            const char *path);

bool czkawka_duplicate_finder_add_excluded_directory(struct CzkawkaDuplicateFinder *finder,
                                                     const char *path);

void czkawka_duplicate_finder_set_recursive(struct CzkawkaDuplicateFinder *finder, bool recursive);

void czkawka_duplicate_finder_set_min_size(struct CzkawkaDuplicateFinder *finder, uint64_t size);

void czkawka_duplicate_finder_set_max_size(struct CzkawkaDuplicateFinder *finder, uint64_t size);

bool czkawka_duplicate_finder_search(struct CzkawkaDuplicateFinder *finder);

void czkawka_duplicate_finder_stop(struct CzkawkaDuplicateFinder *finder);

uintptr_t czkawka_duplicate_finder_get_group_count(const struct CzkawkaDuplicateFinder *finder);

uint64_t czkawka_duplicate_finder_get_wasted_space(const struct CzkawkaDuplicateFinder *finder);

bool czkawka_duplicate_finder_get_group(const struct CzkawkaDuplicateFinder *finder,
                                        uintptr_t group_index,
                                        const struct CDuplicateEntry **out_entries,
                                        uintptr_t *out_count);

void czkawka_duplicate_entries_free(struct CDuplicateEntry *entries, uintptr_t count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CZKAWKA_BRIDGE_H */
